### ISSUE TITLE
Improve BuildMemberRef to autobuild memberRef from _module references.

### ISSUE THREAD

**Issue by SlowLogicBoy** [ioncodes/dnpatch#13]

**Comment by ioncodes** [comment]
An example would be nice aswell as a short description

**Comment by SlowLogicBoy** [comment]
`var memberRef = p.BuildMemberRef("System", "STAThread", ".ctor", Patcher.MemberRefType.Static)`
BuildMemberRef would search for System.STAThread type in references.
```
var typeDef = FindTypeInReferences(namespace, class);
var memberRef = BuildMemberRefToType(typeDef, memberName); //memberName in this case = ".ctor"
return memberRef;
```
Something like that.

This would find and automagically add arguments and return types for that memberRef.

I mean add in
`new MemberRefUser(module, ".ctor", methodSig, staThread);` 
methodSig

**Comment by ioncodes** [comment]
Will do this in the next days, need to make a concept for that first.

**Comment by ioncodes** [comment]
I have now holidays so I got time to build this properly. However, I will throw a hotfix first, because someone contacted me on Reddit.

**Comment by ioncodes** [comment]
https://github.com/ioncodes/dnpatch/commit/efd3dbd83237e2c8229db25c60e12654a69453f1
