### ISSUE TITLE
Add instructions to methodbodies

### ISSUE THREAD

**Issue by erherhh4herh** [ioncodes/dnpatch#19]
Could you please add a feature to add instructions to methodbodies? Thanks :)

**Comment by ioncodes** [comment]
I'm currently working on a full rewrite, so don't expect this to be added in this version.

**Comment by ioncodes** [comment]
Letting you know that this has been implemented in the v1 branch: https://github.com/ioncodes/dnpatch/commit/f80a4c7d3f51a13c18b08e1eb1e46f2ae13386d0#diff-803cb301f9ea1187fc6cba11a6814aaeR39
