### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [ioncodes/dnpatch#2]
A friendly suggestion: consider using a more generic API - for example, instead of requiring file names as constructor parameters (though very useful), please also provide overloads with something more general like a `Stream` - if an app is working with assemblies in memory, this saves the author the trouble of recompiling the `dnpatch` library or using temporary files.

Awesome project, by the way!

**Comment by Rottweiler** [comment]
Added (#3)

**Comment by ioncodes** [comment]
Thanks for the support Rottweiler! If you have questions or other things, you can always contact me over Gitter (See the README)! I appreciate the support! :)
