### ISSUE TITLE
Compile error(error CS1519: Invalid token '=' in class, struct, or interface member declaration)

### ISSUE THREAD

**Issue by gagmeng** [ioncodes/dnpatch#20]
Win7 X64  visual studio 2013
Snapshot:
[http://uimg.in/images/2017/06/22/nsauj.jpg](url)
[http://uimg.in/images/2017/06/22/sJHIW5a.jpg](url)

Thanks.

**Comment by ioncodes** [comment]
Which .NET framework are you targeting?

**Comment by ioncodes** [comment]
I used .NET 4.5.2 now and it works for me. I use VS2017, but when I started the project I was on VS2015 so it should work with that too.

**Comment by gagmeng** [comment]
Thanks for your reply. Maybe i should try it with VS2015 or above.
