### ISSUE TITLE
help with error please

### ISSUE THREAD

**Issue by fl380** [ioncodes/dnpatch#49]
Sorry to trouble you but I'm getting the following error when saving after a WriteReturnBody:

> Unhandled Exception: System.MissingMethodException: Method not found: 'dnlib.DotNet.Writer.MetaDataOptions dnlib.DotNet.Writer.ModuleWriterOptionsBase.get_MetaDataOptions()'.
>    at dnpatch.PatchHelper.Save(String name)
>    at dnpatch.Patcher.Save(String name)
>    at Test_Patcher.Program.Main(String[] args) in E:\Documents\Visual Studio 2017\Test_Patcher\Test_Patcher\Program.cs:line 29

line 29 is p.Save( "test_temp");

I'll be grateful for your assistance please, thanks.

**Comment by gagmeng** [comment]
Pls attach your code.

**Comment by fl380** [comment]
I understand dnlib a bit better now and am using it directly without dnpatch anymore.

Dnpatch was incredibly useful to help me understand dnlib.
