### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by amazingalek** [ioncodes/dnpatch#51]
Hi! Love this project! Are you planning to release a Nuget package?

**Comment by ioncodes** [comment]
Hey there! I'm currently not really mantaining the project in favor of a different personal project! Unfortunately, there is not Nuget package available. I have a full rewrite planned and documented for the new dnpatch though, which will deserve it's own Nuget package :) Thanks for showing interest in the project tho! If you have any questions or feature requests let me know in the issues.

**Comment by amazingalek** [comment]
Thanks for your answer. Do you recommend using the v1 branch instead of master? I'm currently using master and find it very useful, but had to do a small fix to make it work (see PR).

**Comment by ioncodes** [comment]
I do not recommend using the v1 branch as it will deprecate once I start working on it. It's also not feature complete. The master branch is currently feature complete, if you have any fixes shoot them my way. I will accept your PR! Thanks for supporting the project :)
