### ISSUE TITLE
Help with getting the correct type while creating an instruction with buildCall

### ISSUE THREAD

**Issue by loco-choco** [ioncodes/dnpatch#55]
Hello, I was trying to create a instruction which requires "this" as an variable:

![image](https://user-images.githubusercontent.com/58634087/93500862-0ac66a80-f8eb-11ea-97c1-5fd209de761b.png)

But so far I wasn't able to decide what I should place so that `typeof()` can convert it correctly, I've tried `void` but it only threw an error while saving the patch: 

![image](https://user-images.githubusercontent.com/58634087/93501422-cedfd500-f8eb-11ea-87ad-fd05d2244a89.png)

Any kind of help will be appreciated

**Comment by ioncodes** [comment]
Apologies didn't see the issue. Did you manage to figure it out?

**Comment by loco-choco** [comment]
yeah, I gave a look at the other issues and found what I was looking for, thanks anyway
